<a href="https://colab.research.google.com/github/davidghg/DAVEOSPythonStartUpTeens/blob/main/startupteens_complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Variablen

## Integer

In [ ]:
# Integer
beine = 4
beine = int(4.6)
print(beine)

## Float

In [ ]:
# Float
groesse = 35.4
breite = 21.9

## String

In [ ]:
# String
farbe = 'Braun'

# Mengen

## Variablen

In [ ]:
# Integer
beine = 4

# Float
grosse = 35.4
breite = 21.9

# String
farbe = 'Braun'
label = "Hund"

## Sets

In [ ]:
satz = {beine, grosse, breite, farbe, label}
satz = {4, 35.4, 21.9, "Braun", "Hund"}
feature = {4, 35.4, 21.9, "Braun", "Hund"}

## Tupel

In [ ]:
tupel = (4, 35.4, 21.9, "Braun", "Hund")

## Listen

In [ ]:
liste = [4, 35.4, 21.9, "Braun", "Hund"]

## Dictionaries

In [ ]:
# Dictionaries
data = {
    'beine': beine,
    'grosse': grosse,
    'breite': breite,
    'farbe': farbe,
    'label': label
}

In [ ]:
# Doppelte Werte
data = {
   'beine': 4,
   'grosse': 35.4,
   'breite': 21.9,
   'farbe': "Braun",
   'label': "Hund",
   'breite': 28.3
}

In [ ]:
# Auslesen
print(data['beine'])

## Mengen von Mengen

In [ ]:
# Listen erstellen
beine = [4, 4, 4, 4, 4]
grosse = [35.4, 28.6, 32.7, 23.9, 45.6]
breite = [21.9, 18.7, 16.4, 15.8, 25.6]
farbe = ["Braun", "Weiß", "Schwarz", "Beige", "Braun"]
label = ["Hund", "Hund", "Hund", "kein Hund", "Hund"]

In [ ]:
data = {
    'beine': beine,
    'grosse': grosse,
    'breite': breite,
    'farbe': farbe,
    'label': label
}

In [ ]:
print(data['breite'])

# Numpy

In [ ]:
data = {
   'beine': [4, 4, 4],
   'groesse': [35.4, 28.6, 32.7],
   'breite': [21.9, 18.7, 16.4],
   'farbe': ["Braun", "Schwarz", "Beige"],
   'label': ["Hund", "nicht Hund", "Hund"]
}

In [ ]:
beine = [4, 4, 4, 4, 4]
groesse = [35.4, 28.6, 32.7, 23.9, 45.6]
breite = [21.9, 18.7, 16.4, 15.8, 25.6]
farbe = ["Braun", "Weiß", "Schwarz", "Beige", "Braun"]
label = ["Hund", "nicht Hund", "Hund", "nicht Hund", "Hund"]

In [ ]:
farbe = [1, "Weiß", "Schwarz", "Beige", 1]
farbe = [1, 2, "Schwarz", "Beige", 1]
farbe = [1, 2, 3, "Beige", 1]
farbe = [1, 2, 3, 4, 1]
label = [1, "nicht Hund", 1, "nicht Hund", 1]

In [ ]:
beine = [4, 4, 4, 4, 4]
groesse = [35.4, 28.6, 32.7, 23.9, 45.6]
breite = [21.9, 18.7, 16.4, 15.8, 25.6]
label = [1, 0, 1, 0, 1]

In [ ]:
data = {
   'beine': [4, 4, 4, 4, 4],
   'groesse': [35.4, 28.6, 32.7, 23.9, 45.6],
   'breite': [21.9, 18.7, 16.4, 15.8, 25.6],
   'label': [1, 0, 1, 0, 1]
}

In [ ]:
import numpy as np

In [ ]:
beine = np.array([4, 4, 4, 4, 4])
groesse = np.array([35.4, 28.6, 32.7, 23.9, 45.6])
breite = np.array([21.9, 18.7, 16.4, 15.8, 25.6])
label = np.array([1, 0, 1, 0, 1])

In [ ]:
# Mit der eckigen Klammer (als Liste) sieht es so aus:
print(np.array([35.4, 28.6, 32.7, 23.9, 45.6]))

# Und als Tupel genau gleich:
print(np.array((35.4, 28.6, 32.7, 23.9, 45.6)))

[35.4 28.6 32.7 23.9 45.6]
[35.4 28.6 32.7 23.9 45.6]


In [ ]:
beine = np.array(data['beine'])
groesse = np.array(data['groesse'])
breite = np.array(data['breite'])
label = np.array(data['label'])
label.shape

(5,)

In [ ]:
print(breite)

[21.9 18.7 16.4 15.8 25.6]


In [ ]:
data_np = np.array(data)

In [ ]:
feature = np.array([data['beine'], data['groesse'], data['breite']])
print(feature)
print(feature.shape)

[[ 4.   4.   4.   4.   4. ]
 [35.4 28.6 32.7 23.9 45.6]
 [21.9 18.7 16.4 15.8 25.6]]
(3, 5)


In [ ]:
# Zeilen und Spalten tauschen
print(feature.T)

[[ 4.  35.4 21.9]
 [ 4.  28.6 18.7]
 [ 4.  32.7 16.4]
 [ 4.  23.9 15.8]
 [ 4.  45.6 25.6]]
